---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prober
    app.kubernetes.io/component: exporter
  name: prober
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: prober
