---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prober
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prober
    app.kubernetes.io/version: 0.18.0
    app.kubernetes.io/component: exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prober
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prober
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - prober
              topologyKey: kubernetes.io/hostname
      containers:
      - name: prober
        image: quay.io/prometheus/blackbox-exporter:v0.18.0
        imagePullPolicy: IfNotPresent
        args:
          - --config.file=/etc/blackbox_exporter/config.yml
          - --log.level=debug
        ports:
          - containerPort: 9115
            name: http
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 1
          failureThreshold: 5
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /etc/blackbox_exporter
            name: config
            readOnly: true
        securityContext:
          capabilities:
            add: ['NET_RAW']
        resources:
          requests:
            memory: 20Mi
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: prober-config
          name: config
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
