---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: dns
  labels:
    app.kubernetes.io/name: coredns
spec:
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: metrics

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: dns-svc
  labels:
    app.kubernetes.io/name: coredns
  name: dns-tcp
  namespace: dns
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.2.20
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - name: dns
    port: 53
    protocol: TCP
    targetPort: dns
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: dns-svc
  labels:
    app.kubernetes.io/name: coredns
  name: dns-udp
  namespace: dns
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.2.20
  selector:
    app.kubernetes.io/name: coredns
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: dns-udp
