apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - passwordSecret:
        key: password
        name: repo-ankhmorpork.thaum.xyz
      type: git
      url: https://github.com/paulfantom/ankhmorpork.thaum.xyz.git
      usernameSecret:
        key: username
        name: repo-ankhmorpork.thaum.xyz

