---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: holiday-exporter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: holiday-exporter
data:
  holiday_exporter.yaml: |
    main:
      port: 9137
    holidays:
      - country: "DE"
        province: "BE"
      - country: "PL"
    custom_holidays: []
