---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: holiday-exporter
    app.kubernetes.io/component: exporter
  name: holiday
  namespace: monitoring
spec:
  ports:
  - name: http-holiday
    port: 9137
    protocol: TCP
    targetPort: http-holiday
  selector:
    app.kubernetes.io/name: holiday-exporter
