apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: unifi
spec:
  encryptedData:
    pass: AgAdX7t+6altaBhrk3UqW5sTk3aMSBBbJCxGl4zMdgh04636sFKink27EOdCX78yNt89K7KcZzsD+Nm+G3HWb23oGt7eifYtNHHFKCZPpg80wqvKjn4+FV+jOIKUZ0K5iPZ1eFi7rUolxypJ4yb1/bSXb0BU7wOsE3031T4p4aVi9aHEHdOVgmrBvjbQSQYmpexRd/ORCIrJYMYUDt7LG/NP1QHWVZQLWCZAKlFwtl6bCRiSKPUkUUs0/I5UqOdM19ugRjy6zgk4uPgoG8O7Y7q1otEp8QXPOGKX85z89l/FLSCtJo/K/FhSsuDGHa64qFDyKq5ZbUQ6HxULPtN8m6ZJRp3XPf8CQB4XXUmCrpCLKiSIHxGeWV5tPv3X6QjVU27+jp3E9W5h5r9+IyTLZqt46C1FwmqIB9vw3NjGF8LjO39CVaVUzXSyCn5l3qkmRU4sPtXGTIioqx92fnr0AMUMX3BWGqNIuYQws01Jf7i5JcWagjJ3cvN6cHMt0n2OGj11+1hETVg4a61S4Ome6h25y5pugYU9sNeB7at2/6R9Y45+grY6xuWT8xvOzaZQgt91rgpjoPiuEM5ux6sxxhmn1Yb2MybJ4X4mk0NP/nTijaeRUuLpJpPFOMwICWcgMtctF2UiYOQZiMUSxuOi9E7JXRRQFL9/IwUVfmAedbwvXnW9fzygJtmUgyv+dCSXEdu7SkBWJniGKxB2KPtXuNBIZA2pFQ==
    user: AgB506NgLGjFdb1UuW3DAL3X7SnVhaYSbDlMF5sYDKkaVf2r4lmhcDa5SZtuw3FMqte9X7ZWXP5NXX7ciAZrfoV8RqGADSuTmk5yBzxGNJxbbkd/SAHJ/j5Irrs24q81opanzSvdWM4qj2Mh5oNfNHE20P858xEn/Y49AAxaF2otqLnMY7QSevXjUfG7EQCC68V71/CElPV8xnm9RFaRa8epmjc3mWfZJh2vdLeqhbnKmOMlH3hxUq6U9b7Kq1jzL84KviYZUxVJH+/xqIoWnzt8nshVC9HmD0Rbq8+UUg5U2J8PhULGLG/AtjYaoN/SzYumoiQdEwvgOfZHF4fsuI6Aaox8HVA4ITtdiS4Uvypwao36QTgZHXuG8w6u6hKBfEGXYRp9BbjLwJEUhXXbQu+KAaDeSHexmp6QZH5kjFAwpsqZ+ogcEuyzFFQ0YG+6AvaJXBMExr3kTcmByv1QJIQ90TgBzvj6mx36sY0pQNnhCL/XqKI70yIv9rtiwiPTp8p8PL7504O70IXWE+uJ7C6Njc+uV0GOVv0KgOz/dFmiYcO4dgLjjyBo2RAb4th/Wt1E6ZRiMpt4YzV0coWlrlFPNUGHPz1tXmsx9YqZTdSChOAP/oP39K/w2Vs7QEE3gi6vgdvsmpoobjV+TPt7w5cAJalqrQrdOGnSOJLX1sI1odUb1IRbbxnQPHM6xkEiDm4KLERF14C/kg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: credentials
      namespace: unifi
