---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: unifi-poller
  name: metrics
  namespace: unifi
spec:
  ports:
  - name: metrics
    port: 9130
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: unifi-poller
