---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: unifi-poller
    app.kubernetes.io/version: 2.0.1
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: argocd
  name: unifi-poller
  namespace: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-poller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: unifi-poller
        app.kubernetes.io/version: 2.0.1
        app.kubernetes.io/component: exporter
        app.kubernetes.io/managed-by: argocd
    spec:
      containers:
      - env:
        - name: UP_UNIFI_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: credentials
              key: user
        - name: UP_UNIFI_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: pass
        - name: UP_INFLUXDB_DISABLE
          value: "true"
        - name: UP_UNIFI_DEFAULT_URL
          value: "https://192.168.2.7:8443"
        - name: UP_POLLING_MODE
          value: "prometheus"
        image: golift/unifi-poller:2.0.1
        imagePullPolicy: IfNotPresent
        name: unifi-poller
        ports:
          - containerPort: 9130
            name: metrics
        readinessProbe:
          tcpSocket:
            port: metrics
          initialDelaySeconds: 15
          failureThreshold: 5
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 5m
            memory: 20Mi
          limits:
            memory: 100Mi
      restartPolicy: Always
