---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: poller
  namespace: unifi
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: unifi-poller
