---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddns
spec:
  destination:
    namespace: ddns
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/ddns
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

