---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dns
spec:
  description: DNS
  destinations:
  - namespace: dns
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/thaum-xyz/ankhmorpork.git'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external
spec:
  destination:
    namespace: dns
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/dns/external
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: dns
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local
spec:
  destination:
    namespace: dns
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/dns/local
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: dns
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

