--
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging
spec:
  description: Logs management
  destinations:
  - namespace: logging
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/thaum-xyz/ankhmorpork.git'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/logging/loki
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
spec:
  destination:
    namespace: logging
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/logging/promtail
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

