---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
spec:
  description: Monitoring
  destinations:
  - namespace: monitoring
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/thaum-xyz/ankhmorpork.git'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/grafana
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/blackbox
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/pushgateway
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holiday
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/holiday
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/ksm
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smokeping
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/smokeping
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-adapter
# spec:
#   destination:
#     namespace: monitoring
#     server: 'https://kubernetes.default.svc'
#   source:
#     path: apps/monitoring/prometheus-adapter
#     repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
#     targetRevision: HEAD
#   project: monitoring
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/prometheus-operator
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-k8s
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/prometheus
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-main
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/alertmanager
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-events-exporter
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/monitoring/kube-events-exporter
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


