---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: multimedia
spec:
  description: Multimedia
  destinations:
  - namespace: multimedia
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - 'https://github.com/thaum-xyz/ankhmorpork.git'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ombi
spec:
  destination:
    namespace: multimedia
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/multimedia/ombi
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: multimedia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
spec:
  destination:
    namespace: multimedia
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/multimedia/plex
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: multimedia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
spec:
  destination:
    namespace: multimedia
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/multimedia/radarr
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: multimedia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
spec:
  destination:
    namespace: multimedia
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/multimedia/sonarr
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: multimedia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
spec:
  destination:
    namespace: multimedia
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/multimedia/transmission
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: multimedia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

