---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-system
spec:
  destination:
    namespace: storage-system
    server: 'https://kubernetes.default.svc'
  source:
    path: base/storage-system
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

