---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade
spec:
  destination:
    namespace: system-upgrade
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/system-upgrade
    repoURL: 'https://github.com/thaum-xyz/ankhmorpork.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
