kind: pipeline
name: validation
trigger:
  branch:
    - master

steps:
- name: kubeval-apps
  image: garethr/kubeval
  depends_on: [clone]
  commands:
    - kubeval --skip-kinds SealedSecret --strict -d apps/
- name: kubeval-base
  image: garethr/kubeval
  depends_on: [clone]
  commands:
    - kubeval --skip-kinds SealedSecret,Application,CustomResourceDefinition,ClusterIssuer,AppProject --strict -d base/
- name: pluto
  image: renaultdigital/pluto
  depends_on: [clone]
  commands:
  # - pluto detect-files --target-versions k8s=v1.18.0 -d base/ apps/
    - pluto detect-files --target-versions k8s=v1.18.0 -d apps/
- name: images
  image: golang:1.13
  depends_on: [clone]
  commands:
    - apt update && apt install -y jq
    - go get -u github.com/brancz/gojsontoyaml
    - go get -u github.com/estesp/manifest-tool
    - ./hack/checkimages.sh
- name: secrets
  image: golang:1.13
  depends_on: [clone]
  commands:
    - apt update && apt install -y jq
    - go get -u github.com/brancz/gojsontoyaml
    - ./hack/checksecrets.sh

