---
checks:
  exclude:
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "no-read-only-root-fs"
    - "run-as-non-root"
    - "no-extensions-v1beta"  # argocd still uses invalid API
