---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pushgateway
    app.kubernetes.io/version: 1.2.0
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
        app.kubernetes.io/component: exporter
    spec:
      containers:
      - name: pushgateway
        image: quay.io/prometheus/pushgateway:v1.2.0
        ports:
        - name: http-push
          containerPort: 9091
        resources:
          requests:
            cpu: 10m
            memory: 12Mi
