apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: thaum-rules
  namespace: monitoring
spec:
  groups:
  - name: custom node alert rules
    rules:
    - alert: PackagesAvailable
      annotations:
        description: '{{ $value }} packages are available for upgrade. Maybe it is
          time to upgrade?'
        runbook_url: https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/PackagesAvailable.md
        summary: Packages are available for upgrade
      expr: |
        sum by (node,instance) (yum_upgrades_pending) > 200
        or
        sum by (node,instance) (apt_upgrades_pending) > 200
      for: 48h
      labels:
        severity: info
    - alert: RebootRequired
      annotations:
        description: Instance '{{ $labels.instance }}' was upgraded and now requires
          a reboot.
        runbook_url: https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/RebootRequired.md
        summary: Reboot is required to finish package upgrade
      expr: node_reboot_required > 0
      for: 4h
      labels:
        severity: info
  - name: alert rules specific to thaum.xyz
    rules:
    - alert: FederatedPrometheusDown
      annotations:
        description: Remote Prometheus server {{ $labels.instance }} has been down
          for more than 10 minutes.
        runbook_url: https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/FederatedPrometheusDown.md
        summary: Federated prometheus is down
      expr: up{job="lancre"} == 0
      for: 20m
      labels:
        severity: warning
    - alert: FilesystemReadOnly
      annotations:
        description: Filesystem went read-only on {{ $labels.instance }}. Check FS
          for possible corruption.
        summary: Filesystem went read-only possibly due to device error.
      expr: |
        node_filesystem_readonly{fstype=~"(vfat|ext4|xfs)"} != 0
      labels:
        severity: critical
    - alert: TouchscreenNotAvailable
      annotations:
        description: Powercycle device {{ $labels.instance }} to bring touchscreen
          up
        summary: Touchscreen not available
      expr: |
        devices_input_touchscreen_up == 0 or absent(devices_input_touchscreen_up)
      for: 10m
      labels:
        severity: warning
    - alert: TouchscreenNotAvailable
      annotations:
        description: Powercycle device {{ $labels.instance }}
        summary: Touchscreen not available and automatic remediation failed to restore
          it
      expr: |
        devices_input_touchscreen_up == 0 or absent(devices_input_touchscreen_up)
      for: 1h
      labels:
        severity: critical
    - alert: TemperaturesNotAvailable
      annotations:
        description: Temperature data is gone. Immediatelly switch off all relays
          and check OW bus.
        summary: Cannot obtain temperature data
      expr: |
        absent(evok_temperature_celsius)
      for: 15m
      labels:
        severity: critical
