---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: database
  name: mysql
  namespace: nextcloud
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: metrics
    port: 9104
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: database
