---
apiVersion: secrets.mz.com/v1alpha1
kind: ConfigMapSecret
metadata:
  name: mysql-init
  namespace: nextcloud
spec:
  template:
    metadata:
      name: mysql-init
      namespace: nextcloud
    data:
      exporter.sql: |
        CREATE USER '$(MYSQL_EXPORTER_USER)'@'127.0.0.1' IDENTIFIED BY '$(MYSQL_EXPORTER_PASS)' WITH MAX_USER_CONNECTIONS 3;
        GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO '$(MYSQL_EXPORTER_USER)'@'127.0.0.1';
  vars:
    - name: MYSQL_EXPORTER_USER
      secretValue:
        name: mysql-creds
        key: exporter_user
    - name: MYSQL_EXPORTER_PASS
      secretValue:
        name: mysql-creds
        key: exporter_pass
