---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ghost
  namespace: adrianna
  annotations:
    volume.beta.kubernetes.io/storage-class: "external-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
