---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  namespace: adrianna
  labels:
    probe: enabled
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 50M
spec:
  tls:
  - hosts:
    - weirdo.blog
    secretName: ghost-tls
  rules:
  - host: weirdo.blog
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              name: http
