apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configmapsecret-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmapsecret-controller
subjects:
- kind: ServiceAccount
  name: configmapsecret-controller
  namespace: kube-system
