---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: pushgateway
    app.kubernetes.io/component: exporter
  name: push
  namespace: monitoring
spec:
  ports:
  - name: http-push
    port: 9091
    protocol: TCP
    targetPort: http-push
  selector:
    app.kubernetes.io/name: pushgateway
    app.kubernetes.io/component: exporter
