---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http-push
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
