---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: multimedia
  labels:
    app.kubernetes.io/name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
  serviceName: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        name: sonarr
        image: linuxserver/sonarr
        ports:
          - containerPort: 8989
            name: http-sonarr
        readinessProbe:
          tcpSocket:
            port: http-sonarr
          failureThreshold: 5
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /etc/localtime
            name: localtime
            readOnly: true
          - mountPath: /tv
            name: data
          - mountPath: /data/completed
            name: downloads
        resources:
          requests:
            memory: 280Mi
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /srv/netflix/tv
      - name: downloads
        hostPath:
          path: /srv/torrents/completed
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      nodeSelector:
        storage.infra/raid: "true"
      tolerations:
      - key: "node-role.kubernetes.io/storage"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "tier/storage"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "storage.infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: config
      namespace: multimedia
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs-client"
    spec:
      storageClassName: "nfs-client"
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
