---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr-exporter
  namespace: multimedia
  labels:
    app.kubernetes.io/name: exportarr
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/component: exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: exportarr
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/component: exporter
  endpoints:
  - port: sonarr-metrics
    interval: 4m
    scrapeTimeout: 90s
    path: /metrics
