---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          headers:
            Content-Type: text/html
            Content-Encoding: gzip
          no_follow_redirects: true
          fail_if_ssl: false
          fail_if_not_ssl: false
          #      fail_if_header_not_matches:
          #        - header: X-mac-address
          #          regexp: '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$'
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4" # defaults to "ip6"
          ip_protocol_fallback: false  # no fallback to "ip6"
      icmp:
        prober: icmp
        timeout: 15s
        icmp:
          preferred_ip_protocol: "ip4"
          source_ip_address: "127.0.0.1"
