---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
    app.kubernetes.io/version: 0.16.0
    app.kubernetes.io/component: exporter
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - blackbox-exporter
              topologyKey: kubernetes.io/hostname
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.16.0
        imagePullPolicy: IfNotPresent
        args:
          - --config.file=/etc/blackbox_exporter/config.yml
        ports:
          - containerPort: 9115
            name: http-blackbox
        readinessProbe:
          tcpSocket:
            port: http-blackbox
          initialDelaySeconds: 1
          failureThreshold: 5
          timeoutSeconds: 10
        volumeMounts:
          - mountPath: /etc/blackbox_exporter
            name: config
            readOnly: true
        #- mountPath: /etc/blackbox_exporter/config.yaml
        #  name: config
        #  subPath: config.yaml
        #  readOnly: true
        securityContext:
          capabilities:
            add: ['NET_RAW']
        resources:
          requests:
            memory: 20Mi
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: blackbox-exporter-config
          name: config
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
