---
locales_present:
  - en_US.UTF-8
  - en_GB.UTF-8
unattended_automatic_reboot_time: "02:00"

node_exporter_enabled_collectors:
  - textfile:
      directory: "/var/lib/node_exporter"
  - filesystem:
      ignored-fs-types: "^(sys|proc|auto|overlay)fs$"
      ignored-mount-points: "^/(sys|proc|dev)($|/)"
  - diskstats:
      ignored-devices: '^(ram|loop|fd|(h|v|xv)d[a-z]|dm-)\\\d+$'
  - netdev:
      device-blacklist: "^(veth.*|br.*)$"
node_exporter_disabled_collectors:
  - logind
  - ntp
