---
apiVersion: v1
kind: Service
metadata:
  annotations:
    ignore-check.kube-linter.io/dangling-service: "Check is incompatible with prometheus-operator CRDs"
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader
    port: 8080
    targetPort: 8080
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
