---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: exporter
  name: metrics
  namespace: nextcloud
spec:
  ports:
  - name: metrics
    port: 9205
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: exporter
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: exporter

