apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgA7CsZiXCYhSPaMtNXnZaMPqJ4yZKEy8E4UvnNv93bWxGDjVGd+JTcW9/NUK9ZCBEk0iux6I/Ec2F6p65k2gSA4/lssUVK0Dq7Mz+Lz5HKfBRKSUxNjF1GNOMEsCkXMC9USp+2nF0FIMBScH8NxNX5e1vBuQKd5dr9hVd2vgvUFRQ8m/gVV7ZqqJbDnRgxBp7e1ULOBxi7JTkzZMQ2FSe9m99IFZ0uQhNDXmAwy/nxf6s38k9H8BNrhSGrvWlymMa1TTmjAGhlMdz0JH69LP05SCcSQjv1FDcKNv4fRj2+TiMUgsVkffYGPCEAjUmolRNqTwaaht8RnNUlb+HdrmB8vd4gRXoypZ94h4a+c4FpBOffGVZwyqNf6tm5G8cxbD1J6+AwxpdzNE+iWCDuWxr224HsTEHB16FR/UpIsZyazfvL7OoMfhrkAAWKLADHnqy3dp7BCu+gkPX++GdUaVhsjsaT7tq6wiFbtTWegyb2hzeTHbfMKR2urBszkiYYTVu3B22yJG4uxHvLBDCouOG8swAspqGsu0dUJ6mldd8h3hKeydQsNdzmvjWf48ezpGu2ucJfGMlfK76w905qa87Oc89w+rga1+aa+fTYZHaLYKtp3abKXSZuajw+PQWVJRcZW8T/uGoOITXe+pbt3qrOCwsu2oi9s4dtcfFC4BneWssE6LsaZiygVuptH6hTMRJ8eyNCUF6hcDTU8iBvTDBburylvmO6SKTI5v4sOxw==
    NEXTCLOUD_USERNAME: AgB1Q8GoEpds8ttwVGC+2OGLlHscb0p2I2fvYT5uvSfMJLNoM5y/gc0OXOUC6UxzjA9r4rmPYMJfsY8dPzTpoReYFkPozFg/6qG7eQmsQ/LcOC6F0X7/ZIAN6jZT102d/xqPbMrDqmSXc0rMiHDFNhBgjaXZayHYEYnzWyyIV17CD4tV2Y18LTS6QtpQ/8oJ2SmKhNAAeiPoJRfZHJHdlwi6OceEusQhHtA8l5LXhA9xwMTNNtx2D3D4Ll1/XJZ0HJMUZ6oSVYgEuNggDLYUQPW2GPjC5T5qZU8Eg6tFQKiJ/AEKcIna7rBjxDKG3lQtiDRXjvAxF17vMFqeVE1+PLrso+d+J7O3ZXJRn3zCbUu04GrnlcFfXEHeD26pWXsWVklfjXQ9ByiWwE4bNiF0R6Vfclkr3fppUIVfSA+353QWnZ42II2X9n3Ao7uEEUo54trROGC3wuxFWg4buKCjifpJYVkN3emvGKxRTDNaV0sVfL6cOq2BIOl88SRV8jqI3uHLX3fwLGO1D6jeQGwslOyTxo5Ewt3twsMow2fhN52G2pG536qtEYQU3k2RDkCiZS8F3VS0ei+LzRE6kk8VlZs4VEdK4R2UTelFgVKprWFK/DLZvtgYBb9LqPaL0mo4mOKY+NOsP305KDFSK9wHvpA9OgdaMhz2KiUWxDPZVSYm6HSCDzoTwrhZtYuSClAIhGUnA65g4X7NfOv/
  template:
    metadata:
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
