apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exporter
  namespace: nextcloud
spec:
  encryptedData:
    NEXTCLOUD_PASSWORD: AgC7mWzgT3Rhw5dxcYQVgtOykcOb3tof9yBd2/cdUe6dtAAap7wWrfH2GFKhlqQHHDABqz8VYqC/2nuzhVDFkh4qIRzziEOt/eVQlprS4U9NdH6cA6CsjRuL4i8GRhzIxjALC/o6zLsrpYp0m879N60lp2p1DcRtsZ8qM3d91y+WjfqBaDxZ/R24LQ0Ui3JnWNwSvyb2dkX1kHiKZMVjdZwwkHy6mG/Y04XUsipcua7xX7qMkUI9Nzun2nfzaQr3lq2dHRp1kvWDBMxbBAkvmE2wbDXgEvOJQBGRpETPTSGhG2YHkFxu2i8qFXvScwPBV6Tb+2CbCmcpouIgKiqQX7G+ybLTxZOwjNXo8BpRUq4j7dADMYTbUW4URctIH/pr196bELd7vLQQ36rlLd04AnMOqjICir5X7TvLtSACfmn55/IaIhrS8tzTycLP8P9W7UXea48bnNGdE0PmyJH3nz/gqEZSv3mhYHOVcjqwoxlHJpNITJVQ04cFSIUEjZyPK3Z2KmuUtkzTN53WImeupHY3llmkpJy79eKe2dM/9ivTCUtUMoPcUReXRFhGyWFBuut8Nrsrxi8YBnbjMVvRJFxbFnPChvHpXR9zfWAWh+DEPuOemejnVD0WfYEcw8Bb9gsYc23CTk9wDsFmqDmwdFVDiJ503SBKiCQGqTS8iL3xjbXv2DbyosvlfEG3B0mEZPzIW//ZX297I81Lr2MbodL3Oj0RMhCqpAD8F+Zlog==
    NEXTCLOUD_USERNAME: AgAnGJPp3bk+lzFkiqpdkdDSHDENYwUHUqKP4+KVdbyzvMdSeXbM2koltzkdGy/jtIm2qtP3g5f2qLT+YXSShIQ2AIC4Vpw89jjpJ/kA0qyYs+Hj8eCgGmdX9nhXzlB/h115hOw6rdpHJuAFblWWjj6O9F+4WwzrpD2X0NtmsZ2pZSv49sVhThw1HfVkjEcd4f/wKbakoFQyAiKtWmg8a1Lg+/XF7jN8naGYyLwKkHYifUSgZTbHgtM5YBjtOeX4W4R7XlEwMqnx+dnEjUaWYYBj2j/CfolfgsQCQFr+DjhPfBNH9U814mtDRC7sJ5XvbSWpfuoDq14MabZB4kxBb9NGP6vxjs3MRXwKjtd6NdpU+NKzE/joa0UCNsCNp9sW86JLB55ntvrbxwkaXWOEHQGJbb5Om2/Bse7LC0QD36RXTDg6YDLiWnnzOuoJARhBfUjl7/tm7Id8G5ZNlSwU7JWNzDD1NjjT0U2kDjnbfzMdtoxnZDkV/JXRA+Sv+b6lwuAYCAxFh+TkoHb5M3K+ZYnisws324UfQ2z1Ldi7umAQeF/kyxRJQ+ej+b1td/kCf2MqckphbRgdf2IICO/m2EHN7Bd6XJO+TKMFdzodzF+qvQDYEQqcnZ5I5NogXxMEKe32EkK3vwjnhh+h4m9tk0EdGzSo5pqutf7FZfVTffCupGCrN2GqWVyN0+L160tUb1uJ0g3/Pvm5zqa1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: exporter
      namespace: nextcloud
    type: Opaque
