---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ara-database
  namespace: ara
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
