---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "multimedia"
  name: "torrents-incomplete"
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "70Gi"
