apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission-vpn-creds
  namespace: multimedia
spec:
  encryptedData:
    openvpn-credentials.txt: AgC8/3VsJydlzepIuxFhszZo06Xx3xJtRjT2bGKFZullHgOSTeg5WNmLxUUm/abUhFQU98YatffwnexNL1JjQKgUtofbbJCrTb1+3rBNKOU6EIOWc0af23RdbldizNUsWhZPHr3yFmz2CQe/YQBXI5ubp80l4cfpZipWDbgl5tHfenEvfTBmQ95eNsp5PiM3l6viAqHrk7Yl7XtHiQv89ozPOMsG++7/+K+FIUklnZ/W9lFPDj2/TFjkUwEapklo2I6gTtCXG/5VOD4Hwc1egVnOQA+vGLQz2JXOBI7THNHK+nYk1DCB4Bz708BEpsPEfR+ZTN2j92uCouggb/FuJ6++RJDOlCvsRqg8j8SfbfWeRtmkxgav4/flgTc2pE06PqMQgRKJzLSHi7+I4SFJuIxvPSP6qrQDjlNrFL9TudcJ2/jQ/fkRggjrUBNjLJwtY/whB/XDvv18NKt3waZuynvWu+ZUXN9g4mM8Ds3ZDfIHncojQM+O/Qkme5opHb/kwXrqMNgXP3ManZ2owJ3rOk+gsog1rXCCAys6zx5Z0n6Y27bsS8lwj0BEu4NoXU+XwOiNwNTsoCgO9lxr1R2Mfk3RC+lFic3GVcG+aDq/yBpr0VKuJkzUYD45chgaMmbPbdajACA0I3lsKjMO/p17WGtIjT60z5cDLJ/LRTM7SpL/oGYs6BJ8awfpcraRa7ulu+eZhJ6f4/UOTsTdJ+zgfJvKeexnk3j/H7NKBEAU+IaSrl77fpRKGnPoNobNGVXeBjU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: transmission-vpn-creds
      namespace: multimedia
    type: Opaque
