apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
spec:
  encryptedData:
    secretkey: AgBEuXKe5kU0fP2PfMc4BFhA7xcTFmL22DdX6Se4LxXO4MTMMVI0b/8vu9ZphiX2YJC4VD+rI/QCDsymkeFaWAk/GnjhmAXxGm2PChXG/BMWgqAI30r9XSDCBX9lGIt4g2krO+yVGKcIgbjACKShESzRD0B++XxqATa6v7L6y34EjTeOySkfG8+TA+cS+lRdeJuhJ8DPwHQa9Lmqfs6GlmqJqfbQoRcev7k1vCkcnyi772OomghBUhVX1k8XNwrElK55wkbjbpWlB0qmz8hKllCsIhYFbBMzNN07wZZP7TxZh/rBpBzGt9hhG0ITlMdX6H6Px3VhIw2Rxb07kap0p7nGZe/0UsdAXAu5l6AnL6kHWdrXUe+6148bsfoMdgc/PU57H94eOOIp/rEYk1n6E0vyW/IJHE57Gf+bt1tsIFheMZRdjFnJIlZchEU2Cp6FhM3Q5ZlSrG57caBqFAywg7vW1LOPtUtnqE2WdVrDsR2jA6+zg9fIwwnvAn8a0xsjXNhAvm8KAo6vfH5NW3EKd3AWFoiIqeCAApTgt2MpoSPmuZN3wPJbgKN/AxwokkUpggcUaZz373nQmV3HvyUPT2tqayzCstH4KffsEMmrlsyIitrYEdoWFdD09tosoloIDIbgqlLd1i55tGFyD2OIaiTlaepYRuV377cKq31IkO1jpMgHAgrh6apw1blEK7UA/+pazLcGmD8WdwJnB7kWQwNDMJ0UhT+++IpMaVj4xFnxhaUrF+Ffj27ISTfZ3330nmoO1On4Fop4ZfcOfxSG2faV5rzYC1VLrcBEKdj3MAbuCofuuA3TF+wtV4xmG/9NjWZERAYSLHR8Hb0sG6ZTUWaAki06U8+dnsitbCurAhF+M/22DlNSmS5CCW/TRvzZg4sn8rQAepXHrtOlfuoeoAY7wy5bW4lCxaf7lP3McNxh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: memberlist
      namespace: metallb-system
    type: Opaque
