---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metallb
    component: controller
  name: metrics
  namespace: metallb-system
spec:
  ports:
  - name: monitoring
    port: 7472
    protocol: TCP
    targetPort: monitoring
  selector:
    app: metallb
    component: controller
