apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: smokeping
    app.kubernetes.io/version: 1.2.0
  name: smokeping
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9374
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: smokeping
