---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app.kubernetes.io/name: plex
  name: plex
  namespace: multimedia
spec:
  # traffic policy needs to be "Local" to prevent incorrect
  # assumption of client source IP in plex
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.2.98
  ports:
  - name: plex
    port: 32400
    protocol: TCP
    targetPort: plex
  selector:
    app.kubernetes.io/name: plex
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: plex
  name: plex-metrics
  namespace: multimedia
spec:
  loadBalancerIP: None
  ports:
  - name: metrics
    port: 9594
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: plex
