---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: plex
  namespace: multimedia
spec:
  endpoints:
  - interval: 30s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
