---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pihole-custom-addresses
  namespace: pihole
data:
  custom.list: |
    192.168.2.30 cloud.krupa.net.pl
    192.168.2.30 ankhmorpork.thaum.xyz
    192.168.2.30 home.ankhmorpork.thaum.xyz
    192.168.2.30 ombi.ankhmorpork.thaum.xyz
    192.168.2.30 prometheus.ankhmorpork.thaum.xyz
    192.168.2.30 alertmanager.ankhmorpork.thaum.xyz
    192.168.2.30 grafana.ankhmorpork.thaum.xyz
    192.168.2.30 twoflower.ankhmorpork.thaum.xyz
    192.168.2.30 auth.ankhmorpork.thaum.xyz
    192.168.2.7  unifi.ankhmorpork.thaum.xyz
    192.168.2.10 spy.ankhmorpork.thaum.xyz
    192.168.2.20 pihole.ankhmorpork.thaum.xyz

    192.168.2.3  nas.ankhmorpork.thaum.xyz
    192.168.2.11 master01.ankhmorpork.thaum.xyz
    192.168.2.12 node01.ankhmorpork.thaum.xyz
    192.168.2.13 node02.ankhmorpork.thaum.xyz
    192.168.2.14 node03.ankhmorpork.thaum.xyz
    192.168.2.15 node04.ankhmorpork.thaum.xyz
    192.168.2.16 node05.ankhmorpork.thaum.xyz
    192.168.2.17 node06.ankhmorpork.thaum.xyz
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pihole-adlists
  namespace: pihole
data:
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    https://mirror1.malwaredomains.com/files/justdomains
    http://sysctl.org/cameleon/hosts
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/easylist_host.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/easy_privacy_host.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/hostfile.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/Ad_filter_list_by_Disconnect.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/kad_host.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_mobile_host.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/ads-and-tracking.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adservers.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/gambling-hosts.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/youtubehosts.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_host.txt
    https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-pihole-filters/adguard_crypto_host.txt
    https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
    https://v.firebog.net/hosts/static/w3kbl.txt
    https://adaway.org/hosts.txt
    https://v.firebog.net/hosts/AdguardDNS.txt
    https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
    https://v.firebog.net/hosts/Easylist.txt
    https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
    https://www.squidblacklist.org/downloads/dg-ads.acl
    https://v.firebog.net/hosts/Easyprivacy.txt
    https://v.firebog.net/hosts/Prigent-Ads.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
    https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
    https://www.malwaredomainlist.com/hostslist/hosts.txt
    https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
    https://v.firebog.net/hosts/Prigent-Malware.txt
    https://v.firebog.net/hosts/Prigent-Phishing.txt
    https://phishing.army/download/phishing_army_blocklist_extended.txt
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
    https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt
    https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
    https://www.squidblacklist.org/downloads/dg-malicious.acl
    https://zerodot1.gitlab.io/CoinBlockerLists/hosts
