---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pihole
  name: pihole
  namespace: pihole
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app.kubernetes.io/name
                operator: NotIn
                values:
                - prometheus
      containers:
      - env:
        - name: INTERVAL
          value: 15s
        - name: PIHOLE_HOSTNAME
          value: 127.0.0.1
        - name: PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        name: pihole-exporter
        # image: ekofr/pihole-exporter:0.0.9
        image: paulfantom/pihole-exporter
        imagePullPolicy: Always
        ports:
        - containerPort: 9617
          name: metrics
          protocol: TCP
        #readinessProbe:
        #  httpGet:
        #    path: /readiness
        #    port: 9617
        #startupProbe:
        #  httpGet:
        #    path: /readiness
        #    port: 9617
        #  initialDelaySeconds: 5
        #  failureThreshold: 30
        #  periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 9617
        resources:
          requests:
            memory: 15M
        #  limits:
        #    memory: 100M
      - env:
        - name: ServerIP
          value: 192.168.2.20
        - name: DNS1
          value: 1.1.1.1
        - name: DNS2
          value: 192.168.2.1
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-webpassword
        image: pihole/pihole:v5.0
        imagePullPolicy: IfNotPresent
        name: pihole
        ports:
        - containerPort: 80
          name: pihole-http
          protocol: TCP
        - containerPort: 53
          name: dns
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 443
          name: pihole-https
          protocol: TCP
        #- containerPort: 67
        #  name: client-udp
        #  protocol: UDP
        readinessProbe:
          tcpSocket:
            port: dns
          failureThreshold: 5
          timeoutSeconds: 10
        volumeMounts:
        - mountPath: /etc/pihole/custom.list
          name: custom-addresses
          subPath: custom.list
        - mountPath: /etc/pihole/adlists.list
          name: adlists
          subPath: adlists.list
        resources:
          requests:
            memory: 90M
       #   limits:
       #     memory: 250M
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: pihole-custom-addresses
        name: custom-addresses
      - configMap:
          defaultMode: 420
          name: pihole-adlists
        name: adlists
