---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: storage-system
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["%{DEFAULT_LOCAL_STORAGE_PATH}%"]
                }
                ]
        }
