---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notifiers
  namespace: system-update
data:
  github-issue.sh: |
    #!/bin/sh
    set -e
    title="DIUN: New version of $DIUN_ENTRY_IMAGE"
    body="DIUN detected new version of $DIUN_ENTRY_IMAGE available. Consider upgrading."
    payload="{\"title\":\"${title}\",\"body\":\"${body}\",\"labels\":[\"priority/P3\",\"enhancement\"]}"
    touch "/notifiers/${DIUN_ENTRY_IMAGE}.new"
    #curl --fail -L -X POST -d "${payload}" \
    #     -H "Authorization: token ${GITHUB_TOKEN}" \
    #     -H "Content-Type: application/json" \
    #     -H "Accept: application/vnd.github.v3+json" \
    #     "https://api.github.com/repos/${REPO_SLUG}/issues"
