---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http-grafana
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
