---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: storage-system
data:
  default-setting.yaml: |-
    # Settings explained in https://longhorn.io/docs/1.1.0/references/settings/#general
    # backup-target:
    # backup-target-credential-secret:
    # allow-recurring-job-while-volume-detached:
    # create-default-disk-labeled-nodes:
    # default-data-path:
    # replica-soft-anti-affinity:
    # storage-over-provisioning-percentage:
    # storage-minimal-available-percentage:
    upgrade-checker: false
    default-replica-count: 2
    default-data-locality: best-effort
    # guaranteed-engine-cpu:
    # default-longhorn-static-storage-class:
    # backupstore-poll-interval:
    # taint-toleration:
    priority-class: high-priority
    # auto-salvage:
    # auto-delete-pod-when-volume-detached-unexpectedly:
    disable-scheduling-on-cordoned-node: true
    # replica-zone-soft-anti-affinity:
    # volume-attachment-recovery-policy:
    # node-down-pod-deletion-policy:
    # allow-node-drain-with-last-healthy-replica:
    # mkfs-ext4-parameters:
    # disable-replica-rebuild:
    # replica-replenishment-wait-interval:
    # disable-revision-counter:
    # system-managed-pods-image-pull-policy:
    # allow-volume-creation-with-degraded-availability:
    # auto-cleanup-system-generated-snapshot:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-storageclass
  namespace: storage-system
data:
  storageclass.yaml: |
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: longhorn
    provisioner: driver.longhorn.io
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    parameters:
      numberOfReplicas: "2"
      staleReplicaTimeout: "2880"
      fromBackup: ""
    #  diskSelector: "ssd,fast"
    #  nodeSelector: "storage,fast"  # Those are tags set in longhorn UI
    #  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"*/1 * * * *", "retain":1},
    #                   {"name":"backup", "task":"backup", "cron":"*/2 * * * *", "retain":1,
    #                    "labels": {"interval":"2m"}}]'
