---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: longhorn-manager
  name: longhorn-backend
  namespace: storage-system
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: longhorn-manager
  ports:
  - name: manager
    port: 9500
    targetPort: manager
#---
#kind: Service
#apiVersion: v1
#metadata:
#  labels:
#    app: longhorn-ui
#  name: longhorn-frontend
#  namespace: storage-system
#spec:
#  type: ClusterIP
#  selector:
#    app: longhorn-ui
#  ports:
#  - name: http
#    port: 80
#    targetPort: http
#    nodePort: null
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: default
  labels:
    app: longhorn-ui
  name: longhorn-frontend
  namespace: storage-system
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.2.97
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: longhorn-ui
  sessionAffinity: None
  type: LoadBalancer
