---
apiVersion: v1
kind: Secret
metadata:
  name: system
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get upgrade -y
    if [ -f /run/reboot-required ]; then
      cat /run/reboot-required
      reboot
    fi
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: system
  namespace: system-upgrade
spec:
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: plan.upgrade.cattle.io/system
        operator: Exists
      - key: plan.upgrade.cattle.io/system
        operator: NotIn
        values: ["disabled", "false"]
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Equal
      value: "true"

  serviceAccountName: system-upgrade
  secrets:
    - name: system
      path: /host/run/system-upgrade/secrets/system

  # See https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/#use-kubectl-drain-to-remove-a-node-from-service
  drain:
    # deleteLocalData: true
    ignoreDaemonSets: true
    force: true

  version: bionic
  # A very limited container spec
  upgrade:
    # The tag portion of the image will be overridden with the value from `.status.latestVersion` a.k.a. the resolved version.
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/system/upgrade.sh"]
