---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app.kubernetes.io/name: nfs-client-provisioner
  namespace: storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-client-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nfs-client-provisioner
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: thaum.xyz/nfs-client-provisioner
            - name: NFS_SERVER
              value: 192.168.2.3
            - name: NFS_PATH
              value: /srv/kubernetes/nfs
          name: nfs-client-provisioner
          # image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          image: quay.io/external_storage/nfs-client-provisioner-arm:v3.1.0-k8s1.11
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-client-root
      serviceAccount: nfs-client-provisioner
      serviceAccountName: nfs-client-provisioner
      priorityClassName: system-cluster-critical
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.2.3
            path: /srv/kubernetes/nfs
      nodeSelector:
        kubernetes.io/arch: arm
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
