---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config
  namespace: homeassistant
  annotations:
    volume.beta.kubernetes.io/storage-class: "longhorn"
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
