---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  endpoints:
  - interval: 90s
    port: webui
    path: /api/prometheus
    bearerTokenSecret:
      name: credentials
      key: token
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: homeassistant
spec:
  encryptedData:
    token: AgCWwBiSdXfwjJbk9gm9sjvQtne/4DqzmeTnGCw6YVyjUnF6MUkMT+ZcYp5XZOR1Aym7UtVvFHj2jLX6Io6L5hznzUk6xw4FensCR+itos6eA9j2HmNKHRQUbhoMONBYOvBrIEMV2Zx0Cgw3EtNl3FZNf6xKjp2LmsaAcwde6EH4+YVKJc5OFlPU8xwTlNPp3W1Z76Ied0krcv0husymW9x2OEk4gpXUjNGZcx2lS2iRFej6WFgKIbTMmrxNob2HPStiAHUkQ0iAmAVLL1Xpwd7y4hZY0L/tA/zhuqgEVb+I2TgriCDvIc9GhnAJ7zysT6AGiN8zi+UVwTGMhcIqProrJrc3Xwixf6NKoyxR86E41q4MPtNggLaNRWdYiufKfrfTpKRnhubRZEdLugQeD6iEY6AzCPiEtE2sssAcvI39+H7Ia/S4TQIBYUetE4iCVYU4yLo2gfn8ze3R0h2JjFA4DdQQweCOW9R84NzpeAc9lqUr4J3k4So8pr6hS5pGFxQkvgOVGYBEjkw8Wny0DbwUGFIawN7baB/3NXoO5bYiAjrzohBNhJzIGD4dN5JEe7DaT0xc8cDL8Btl//5Swcwrhvm0GUPPGCMSdkk3EfIANpCqULrWhBoSkRSMt2Et3VFq0zRkBOb5LyjDYCA5RmvDJsAULavpOplHARTv6uhGIwp5DBSwhG/hs+SKu15a7WYoy353LfWb6/ZeSam9VBOl5yoX2lUZJ0524PCAjgoUq/PPd5dx9fTHEJ+k3IQf3Tg0jOAJjpuylmKsy0L3BLRt8JreU0rOml+2pgXQKtaoO23PTBhkywmkaDhPR8cUk9oSufpTYMpwFeXgb6BvEdONXal0PDnMKPGsEataCdgzXYw7yWuQcXx7o/ncrGPkIflKBptmNZacBXjJmjM3ZfBLF89DhapY7eJ74hxglu9jS5Jq81a6Yws=
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: homeassistant
    type: Opaque
