---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  endpoints:
  - interval: 90s
    port: webui
    path: /api/prometheus
    bearerTokenSecret:
      name: credentials
      key: token
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: homeassistant
spec:
  encryptedData:
    token: AgA66/fvdQ500dRr7GFHsxoyg2OWVWBYhqB310buBUO1iGybJUgnWESF+ND19itHzNsKvkbBdbhl3j1eQvXqz0vs0LOokzpuo7vLa+h8lugmBWU4sH4+OReEzxHC0bZ0C36aOFY99YysZpN7oXmqdqDFy3Tj4X3NlpHgALx8ZEtz/evSnU4VLIZXkBRFFTtkpMQriQJ5bZpyI7S2NcVNj6TkPiHlhRquls9KkpDyOuj+k4MWSfbp6j1/HINMLqo2Eg0O2cJTG2ZdjWcpjeIGFqZ2HNoY80MGp2vzKotrA/Kl9UkASzsd9pREz/UhN9oRkZHewKhsvnGVihu0Z9J8/n6nyT4qXxCLNmh92SCU0RyzS5ufX/4HZ+Q9PKZ78Eg97dSCK6XrX2aXyuxLwfxa86FZncMPxTwdUYM1vdR6NW8wbmLwyu1LGJK7dL2SIMu5lmFUwdriLc6pHAVWnxkB73ZEeU8I7Y5AVQaHajcPmA2peINS7kRBdTgIlRmsNp6z/+34odZtm3DyTR3f8GDuV1/KTB2MHVGgC/7oz0mcHa5cGLCB5SD8mHEvMNy0EUlI30ir2X+4cZWn3ujtGhDsEwsk1olRPOk6C3H2OMZAeADlKib58QLH/Yfbecg4wWjFUyGSr5snmjdqDfn1Aa9NSS7/CxfmHmJRshC+qVV6IaH9M1+Vw/4neSGPFjntKZbDKSM3detnEXxWwhxhV6w/uMquGkGnVjS3/58116WTKEnAds0hJvoHr17DWD7Voh330I7SStCJNFRpiG1oIZZhy7WkU+ReGqJ1F7HaZ1y6yEMd+RKTirIkIYQOwVO2kMc20dapYg8O5kMYQMPXN0OwIsFXN0JW/bMgs/xXMrsfsYD+AKs1TuKMsWOoxK9eGKpxu+wciXoBl0qlQ0n//SZDRFT0MITcWXPc1MkIPAhM+XBufy2IrlMyCoQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: credentials
      namespace: homeassistant
    type: Opaque
