apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: homeassistant-rules
  namespace: homeassistant
spec:
  groups:
    - name: homeassistant alert rules
      rules:
      - alert: HomeAssistantDown
        expr: up{job=~"home-assistant.*"} == 0
        for: 30m
        labels:
          severity: critical
          priority: P1
        annotations:
          summary: "Home Assistant instance {{ $labels.instance }} is down"
          description: "Home Assistant is down"
