---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
  name: external-nfs-provisioner
  namespace: storage-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
  name: external-nfs-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
  name: run-external-nfs-provisioner
subjects:
  - kind: ServiceAccount
    name: external-nfs-provisioner
    namespace: storage-system
roleRef:
  kind: ClusterRole
  name: external-nfs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
  name: leader-locking-external-nfs-provisioner
  namespace: storage-system
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
  name: leader-locking-external-nfs-provisioner
  namespace: storage-system
subjects:
  - kind: ServiceAccount
    name: external-nfs-provisioner
    namespace: storage-system
roleRef:
  kind: Role
  name: leader-locking-external-nfs-provisioner
  apiGroup: rbac.authorization.k8s.io
