---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-nfs-provisioner
  labels:
    app.kubernetes.io/name: external-nfs-provisioner
    app.kubernetes.io/version: 3.1.0
  namespace: storage-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: external-nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-nfs-provisioner
        app.kubernetes.io/version: 3.1.0
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: thaum.xyz/external-nfs-provisioner
            - name: NFS_SERVER
              value: 192.168.2.40
            - name: NFS_PATH
              value: /srv/storage/kubernetes/externalnfs
          name: external-nfs-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11
          volumeMounts:
            - mountPath: /persistentvolumes
              name: external-nfs-root
      serviceAccount: external-nfs-provisioner
      serviceAccountName: external-nfs-provisioner
      priorityClassName: system-cluster-critical
      volumes:
        - name: external-nfs-root
          nfs:
            server: 192.168.2.40
            path: /srv/storage/kubernetes/externalnfs
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: "storage.infra"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
