---
- hosts: all
  become: true
  any_errors_fatal: true
  roles:
  - { role: oefenweb.locales, when: (ansible_os_family == "Debian") }
  - { role: jnv.unattended-upgrades, when: (ansible_os_family == "Debian") }
  - dev-sec.ssh-hardening
  - cloudalchemy.node-exporter

- hosts: all
  become: true
  serial: 1
  roles:
  - system
  tasks:
  - name: Reboot PC once a week
    cron:
      cron_file: /etc/crontab
      name: reboot
      user: root
      day: "4"
      hour: "3"
      minute: "43"
      job: reboot
      state: "{{ 'present' if reboot_enabled else 'absent' }}"
    when: reboot_enabled is defined
  - name: Install dependencies
    package:
      name: moreutils
      state: present
  - set_fact:
      pkg_mgr: "{{ 'yum' if ansible_pkg_mgr == 'dnf' else ansible_pkg_mgr }}"
  - name: Copy package manager textfile collector script
    copy:
      src: "scripts/{{ pkg_mgr }}.sh"
      dest: "/usr/local/bin/{{ pkg_mgr }}.sh"
      mode: 0755
  - name: Set cronjob for package manager (/etc/crontab)
    cron:
      cron_file: "/etc/crontab"
      user: root
      name: "{{ ansible_pkg_mgr }}-metrics"
      minute: "13"
      job: "/usr/local/bin/{{ pkg_mgr }}.sh | sponge /var/lib/node_exporter/{{ pkg_mgr }}.prom"

- hosts: raspberry
  become: true
  any_errors_fatal: true
  roles:
  - rpi

- hosts: fancontroler
  become: true
  roles:
  - fans
