---
- hosts: master01
  become: true
  vars:
    log_file: /var/log/deploy/deployment.log
    deploy_script: "{{ playbook_dir }}/../deploy.sh"
    ara_server: "http://192.168.2.25:8000"
  handlers:
  - name: reload systemd
    systemd:
      name: "{{ item }}"
      enabled: true
      daemon_reload: true
    with_items:
      - deploy.service
      - deploy.timer
  tasks:
  - name: Create log directory
    file:
      state: directory
      path: "{{ log_file | dirname }}"
      owner: root
      group: root
      mode: 0755
  - name: Add tmpfiles.d entry to create log dir on boot
    copy:
      content: |
        D {{ log_file | dirname }} 0755 root root - -
      dest: /etc/tmpfiles.d/deploy.conf
  - name: Log rotation setup
    copy:
      content: |
        {{ log_file }}
        {
                rotate 7
                daily
                missingok
                notifempty
                delaycompress
                compress
        }
      dest: /etc/logrotate.d/deploy
  - name: Add automatic deployment systemd service
    copy:
      content: |
        [Unit]
        Description=Ansible automatic deployment
        After=network-online.target
        [Service]
        Type=simple
        Nice=-19
        Environment=PATH=/usr/local/bin:/usr/bin:/bin
        ExecStart={{ deploy_script }} {{ ara_server }}
        StandardOutput=file:{{ log_file }}
        StandardError=file:{{ log_file }}
        SyslogIdentifier=deploy
        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/deploy.service
    notify: reload systemd
  - name: Add automatic deployment timer
    copy:
      content: |
        [Unit]
        Description=Ansible system update
        [Timer]
        OnUnitActiveSec=5m
        [Install]
        WantedBy=timers.target
      dest: /etc/systemd/system/deploy.timer
    notify: reload systemd
