---
apiVersion: secrets.mz.com/v1alpha1
kind: ConfigMapSecret
metadata:
  name: scrapeconfigs
  namespace: monitoring
spec:
  template:
    metadata:
      name: scrapeconfigs
    data:
      additional.yaml: |
        - job_name: windows
          static_configs:
          - targets:
            - 'dibbler.ankhmorpork.thaum.xyz:9182'
        - job_name: lancre
          scrape_interval: 15s
          scheme: 'https'
          honor_labels: true
          metrics_path: '/federate'
          basic_auth:
            username: $(USERNAME)
            password: $(PASSWORD)
          params:
            'match[]':
              - '{job=~".+"}'
          static_configs:
            - targets: ['lancre.thaum.xyz']
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: "prometheus_notifications_alertmanagers_discovered"
              action: drop
            - source_labels: ['instance', 'environment']
              regex: "(.*):(.*);(.*)"
              replacement: '$1.$3:$2'
              target_label: 'instance'
            - source_labels: [state]
              regex: '(activating|deactivating)'
              action: drop
            - source_labels: [type]
              regex: '(oneshot|dbus|idle|notify)'
              action: drop
  vars:
    - name: USERNAME
      secretValue:
        name: federation-creds
        key: lancre_username
    - name: PASSWORD
      secretValue:
        name: federation-creds
        key: lancre_password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: federation-creds
  namespace: monitoring
spec:
  encryptedData:
    lancre_password: AgCI+QiNGdofdbNef+mZP6Q1c4NeMUea8GkhigTyT7TtEanGXhX3i1lJLHHMmYxYrni3xniDzvDR/pt/y021ghm0eXAnWFS50GwQyrykNs7EXlFZa/Tg3YAjzkuUX9ftM/VaHBGYkFqaHWYxOKbACqAr1jrkrWT7a1G9tMoV52igEPPeNnJLRi6B7ys7J1IksEZHZchxGn4njgAHE74govoEVJUrHgqxyVmeEoqG1UM+N94I+BzVJ/zMaVx8+lLl9NuPONAAelfUfnGizl5wS/JjIal7HcQ5Y+hXXtV8AVRiJpRcwgoTpjdqDF7S6ayNfa2xOKu0OEN6uRzQqmhBUfjeaRO1RCqld8qOBUjupNiNfu0Wb+giBJCCiUn6NpbK/pnR/N0ZaCh6zAw6A2vyA5cwCpHh642N9nIA1q77M78AllvQCXu+gcD1R69HAozvyw1D1kadf2SX9AhNy+kGbxGNShKuuGjJ506fwhk23qH2tsVq/DI4B2tzlQz4b0b9ONA/BLFbNSP/TWpO6YkQe6S+OFucNUwWWnsiIysSQCrK4G47oaOzpnFV6bIM/zaL0jx86VU64KQMPVIxzhH/3FFO01OIqyPE9cqXqavYW36eMz1I2UTEuZBTnfI/fx6vIkXG6ZalPc33w1qPCNK7yHTrBz+rP14YrYszA6/sAg3W1tjTG20+JKrErXE4xvQ+H2SqAxDxQcX0UfXzULgLr2XUSvt06dBzc2eAE7LjNg8=
    lancre_username: AgClxVwzL2l3/+hNbfWCqQiQtdxp+W9/q4fskZ3zqS7E4yBRwzM8ReNb2gh3Q6RgwP/pwnHumwYLnyfYIFu/4iMW4El/P6M0FN7Tef94RtD53MIGbc9f3QXSrWJjgZTJVHO67+1YTV2AG0w9wd61YM02PHVICt7Ejt3XkAcl6PmIH2KC1exr0ISeksSktdmoglbUYn3nymzM0BIXKnLyErPkGFg5vuVtqDLZq/IVqphNw4SpqzfnxdZcIW3krXE9mBl9dGNuYMGqimN/dYg0WPmvb/4fCDmwe6D3bSyACo1/dQnYzjBLj/aH1ytYj9OHgjtIH6bi2XODh2wXKkHtEKdgtnQDEYq1SM9ADrnTOvRwGs/zc6pbM52RfcBoOZfc+9fTotMNTQ+xbKdvOZKAH5M5JrGX+PrN7Gv7i4Q1IXHdIjYiC35sqeKr/ZA9xH8YUrfVh6RUqlUVlu6ED+OciY5cUilc+21m/hPazkv1VEtAzWTuDpYWOVwidmD1sgTvlMrc4ZjW/b6jd8ARwbsR6zPXI1yBqk+zo4Iviqq9gY9ffbF1SEiV8q0LfQjgIrXI4SRLxtYAmlUQrWipfiGEHv+LLFXrjkv08O1yI5RSjExnrGQxb0jgi1YhwTNrMeu8Nqxw5z5Rfeu5FaHznQH0g2cZBosGA2HOv3kBynBKVYHDo6I1uBb1N3AO0HqLkwYD3NP8k58WDDd6iV9G
  template:
    metadata:
      creationTimestamp: null
      name: federation-creds
      namespace: monitoring
    type: Opaque
