---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: smokeping
    app.kubernetes.io/component: exporter
  name: smokeping
  namespace: monitoring
spec:
  ports:
  - name: http-smokeping
    port: 9374
    protocol: TCP
    targetPort: http-smokeping
  selector:
    app.kubernetes.io/name: smokeping
