---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: smokeping
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: exporter
  name: smokeping
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: smokeping
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smokeping
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 10
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - smokeping
              topologyKey: kubernetes.io/hostname
      containers:
      - image: quay.io/superq/smokeping-prober-linux-arm64:master
        imagePullPolicy: IfNotPresent
        name: smokeping
        args:
          - "8.8.8.8"
          - "1.1.1.1"
          - "lancre.thaum.xyz"
          - "rim.thaum.xyz"
          - "krupa.net.pl"
          - "cloud.krupa.net.pl"
          - "pawel.krupa.net.pl"
        ports:
          - containerPort: 9374
            name: http-smokeping
        readinessProbe:
          tcpSocket:
            port: http-smokeping
          initialDelaySeconds: 1
          failureThreshold: 5
          timeoutSeconds: 10
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        resources:
          requests:
            cpu: 40m
            memory: 30Mi
          limits:
            memory: 70Mi
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/arch: arm64
