---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smokeping
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http-smokeping
  selector:
    matchLabels:
      app.kubernetes.io/name: smokeping
