---
# FIXME: WTF, why there are 2 services???
# Source: loki/templates/service-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 2.0.0
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: loki
spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
---
# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: 2.0.0
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: loki
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
