---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
  name: loki
  namespace: logging
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/component: server
