---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: database
  name: redis
  namespace: nextcloud
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: redis
  - name: metrics
    port: 9121
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/component: database
