apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password
  namespace: nextcloud
spec:
  encryptedData:
    REDIS_HOST_PASSWORD: AgBcJXGmx8Zu/aiJZCgzxXh5/UR8aeZ+oMREhnJWha8+NSGjeOXe+dH/UjM32pjIMs7uLVb9VoAzQIk/RMjuOozqnnz0iFe7YyvURm9p0YYrCLaabwa0had8Fy9OV0m+asi1oimtRS4RFEBd7II6jFoCPUQury6qJV7EsJfkdzQsxlPeRPpRvdZdDVsnhEF/O0DUIgrLgRZwNuZf9C5yYatYHkBEiM70S0WjaQmppUd1zUJR8ahWWpyspc9Q5c22JN4r8QlpE10HBt21lHp1tXuEV4MSF9l1S0AokWzv9J7eHUGQ9wkaklrvaHcIqlKZZabtWcKxVnQ3XYfVqvxVbP/nfSdRx6l3l4AY09jCSUI09CDoUFI7x6tHWVkpx3/V8C/444sNKyzlc3mwYKTrxPW5znjW+5FDLk+F2fasU4ypJhGZz18NJbra8gpbVJTnld0tVKAKnE4NREBab65n8dKq2A32tFdaa+uBiBVpt+rzGi0gq25ugCZGcjfEhhVl6yOQLXlOVeCArn6mzOkUq57TvO9jVrDfYBBMzI20yiqWLApIcx9IWb7x8JU5vJf9UDCXaVGxES733rJ3VNC4I6ZdDSPOtsDQF6iup8wKlJZVkyRlfp7XskAn7bUas2DDlUU0AGn4vmt6LIJKQawytwzEMD+WHbFn5S/keYNzx6yDMKRwzHdp9SjoK27nhA9vZQNX/2Wv40fZTqDVBgfzrnwaR+VbUIyC9lTuvg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: redis-password
      namespace: nextcloud
