---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-files
  namespace: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-apps
  namespace: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config
  namespace: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-theme
  namespace: nextcloud
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
