---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
  name: phpfpm
  namespace: nextcloud
spec:
  ports:
  - name: phpfpm
    port: 9000
    protocol: TCP
    targetPort: phpfpm
  - name: phpfpm-metrics
    port: 9253
    protocol: TCP
    targetPort: phpfpm-metrics
  selector:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/part-of: nextcloud
