apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: nextcloud-rules
  namespace: nextcloud
spec:
  groups:
    - name: mysql alert rules
      rules:
      - alert: MySQLDown
        expr: 'mysql_up == 0'
        for: 5m
        labels:
          severity: warning
        annotations:
          message: "MySQL instance {{ $labels.instance }} is down"
      - alert: MySQLInnoDBLogWaits
        expr: rate(mysql_global_status_innodb_log_waits[15m]) > 10
        labels:
          severity: warning
        annotations:
          description: The innodb logs are waiting for disk at a rate of {{$value}} / second
          summary: MySQL innodb log writes stalling
    - name: redis alert rules
      rules:
        - alert: RedisDown
          expr: 'up{job="redis"} != 1 or redis_up != 1'
          for: 10m
          labels:
            severity: warning
          annotations:
            message: >
              The redis exporter failed to fetch metrics from the redis instance for more than 10 minutes.
              This could be because the redis process is down or redis has issues with responding to requests.
        - alert: OutOfMemory
          expr: redis_memory_used_bytes / redis_total_system_memory_bytes * 100 > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Out of memory (instance {{ $labels.instance }})"
            description: "Redis is running out of memory (> 90%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - alert: ReplicationBroken
          expr: delta(redis_connected_slaves[1m]) < 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Replication broken (instance {{ $labels.instance }})"
            description: "Redis instance lost a slave\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - alert: TooManyConnections
          expr: redis_connected_clients > 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Too many connections (instance {{ $labels.instance }})"
            description: "Redis instance has too many connections\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - alert: RejectedConnections
          expr: increase(redis_rejected_connections_total[1m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Rejected connections (instance {{ $labels.instance }})"
            description: "Some connections to Redis has been rejected\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
    - name: nextcloud alert rules
      rules:
      - alert: NextcloudProxyDown
        expr: 'nginx_up{instance="nginx-metrics.nextcloud.svc:9113"} == 0'
        for: 5m
        labels:
          severity: critical
          priority: P1
        annotations:
          message: "Nextcloud nginx proxy server has been down for more than 5 minutes."
      - alert: NextcloudDown
        expr: 'nextcloud_up != 1'
        for: 15m
        labels:
          severity: warning
        annotations:
          description: "Nextcloud seems to be down for more than 2 minutes."
          summary: "Nextcloud is down"
      - alert: NextcloudSpaceFillingUp
        annotations:
          description: "Nextcloud instance at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up."
          summary: "Nextcloud is predicted to run out of space within the next 24 hours."
        expr: |
          (
            nextcloud_free_space_bytes < 5 * 1024 * 1024 * 1024
          and
            predict_linear(nextcloud_free_space_bytes[6h], 24*60*60) < 0
          )
        for: 1h
        labels:
          severity: warning
      - alert: NextcloudSpaceFillingUp
        annotations:
          description: "Nextcloud instance at {{ $labels.instance }} has only {{ printf \"%.2f\" $value }}% available space left and is filling up."
          summary: "Nextcloud is predicted to run out of space within the next 4 hours."
        expr: |
          (
            nextcloud_free_space_bytes < 5 * 1024 * 1024 * 1024
          and
            predict_linear(nextcloud_free_space_bytes[6h], 4*60*60) < 0
          )
        for: 1h
        labels:
          severity: critical
