---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: phpfpm
  namespace: nextcloud
spec:
  endpoints:
  - interval: 30s
    port: phpfpm-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: phpfpm
      app.kubernetes.io/part-of: nextcloud
