---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall-config
  namespace: heimdall
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
