apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: heimdall
  labels:
    app.kubernetes.io/name: backup
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  schedule: "13 1 * * sun"  # At 01:13
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: quay.io/paulfantom/restic-mysql
            env:
              - name: DATA_DIRECTORY
                value: "/backup"
              - name: NAMESPACE
                value: "heimdall"
              - name: INSTANCE
                value: "backup"
              - name: PUSHGATEWAY_URL
                value: "http://push.monitoring.svc:9091"
            envFrom:
              - secretRef:
                  name: restic-repository
            volumeMounts:
              - name: content
                mountPath: /backup
                readOnly: true
          volumes:
            - name: content
              persistentVolumeClaim:
                claimName: heimdall-config
          restartPolicy: OnFailure
