---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app.kubernetes.io/name: homer
    # app.kubernetes.io/version:
spec:
  # replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homer
    spec:
      containers:
      - name: homer
        image: b4bz/homer
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http-homer
        #readinessProbe:
        #  httpGet:
        #    path: /manifest.json
        #    port: http-homer
        #  failureThreshold: 3
        #  timeoutSeconds: 10
        #livenessProbe:
        #  httpGet:
        #    path: /manifest.json
        #    port: http-homer
        #  initialDelaySeconds: 60
        #  failureThreshold: 5
        #  timeoutSeconds: 10
        volumeMounts:
          - mountPath: /www/assets/config.yml
            name: config
            subPath: config.yml
        resources:
          requests:
            cpu: 30m
            memory: 100Mi
          limits:
            memory: 200M
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: config

