---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
  labels:
    app.kubernetes.io/name: homer
    app.kubernetes.io/version: 20.12.19
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: homer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homer
        app.kubernetes.io/version: 20.12.19
    spec:
      affinity:
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - weight: 100
             podAffinityTerm:
               labelSelector:
                 matchExpressions:
                   - key: app.kubernetes.io/name
                     operator: In
                     values: ["homer"]
               topologyKey: kubernetes.io/hostname
      containers:
      - name: homer
        image: b4bz/homer:20.12.19
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: http-homer
        #readinessProbe:
        #  httpGet:
        #    path: /manifest.json
        #    port: http-homer
        #  failureThreshold: 3
        #  timeoutSeconds: 10
        #livenessProbe:
        #  httpGet:
        #    path: /manifest.json
        #    port: http-homer
        #  initialDelaySeconds: 60
        #  failureThreshold: 5
        #  timeoutSeconds: 10
        volumeMounts:
          - mountPath: /www/assets/config.yml
            name: config
            subPath: config.yml
        resources:
          requests:
            cpu: 1m
            memory: 2Mi
          limits:
            cpu: 10m
            memory: 10Mi
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: config

