---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubeseal
  namespace: kube-system
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: kubeseal
