# All this needs to be removed after migration to ZFS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
  namespace: multimedia
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /srv/storage/kubernetes/vod/movies
    server: 192.168.2.40
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
  namespace: multimedia
spec:
  capacity:
    storage: 4000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /srv/storage/kubernetes/vod/tv
    server: 192.168.2.40
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: multimedia
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  namespace: multimedia
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4000Gi
