---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backups
  namespace: unifi
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 900Mi
