apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-locations
  namespace: nextcloud
spec:
  encryptedData:
    pzptg.conf: AgAm/c00PKvWJjmULKhJTo9H/tZYA3iyn8T4NU93spOpm4FVp21Ba/ZtX6sqtVT1plhOF/vensgi/Z1h4fld8l37nwXeyXFQdBlNV2hVm95EbN6cmI88gNhh+ruTIKzLeRN2E6yYvbkDAY4u3hfhmy8tARSFQUi1ct9AILBqEvY4UKgxDR3eB2yiE88MUyhTm+5Ldn4VusQ7cQ4KNh/kMSZ6WnislK+7YGlxd8/jmM1bPvllUUdXSUw38vQcd+1LSh2zhpGmBNg3T8PWL3pRjzx1HR4CTI6DuE+qroPkZNcf3JDq+D9sfhY1yn0R1+nuEQKnFxQJC/L035/q0XINObfiv5xksReEbZFt+EdPx/Gxln+cgpnXaN0uy115Iy8C+d6uTNtDuJejyIIzM1GtRgE9SGebts4OiOnDOpCeMFPhFFfBpsB48bJGa/mFodTXotWMiirtJMIdvq+L3PrvrdH+KmdvnB1+1IYvGxsIB4wI2C9Qp/sGjH/7sBdK4Jkeayo8SoQ4Y4lEBvRQBA6ZwW6rNSTX/beAexCqFOWEy4Ued8jm3dfBruHwlAkWhVY5BmjEtWAEGKViYR7l27KWsTJiSt7KptuQCjP8dzEudhlWwbdGiNdZc9/XXxJH/Y32UCESbZQnEiy3EK6Ckxk9RAqsayDtz2283sE9q5rGreRzzEUqA8GX/cBXTbAOkUowgrkohuz0upJFcdZM9dp46oHoYDPsbjQIcrm8kn/BDiMkYV0yv+9DlZmoEMA7tNqzzYwrAN6dCZ/l3eFWIRtuCEA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: nginx-locations
      namespace: nextcloud
    type: Opaque
