---
name: kubeval

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go get -u github.com/instrumenta/kubeval
      - run: kubeval --skip-kinds Plan,SealedSecret,ConfigMapSecret,CustomResourceDefinition,ServiceMonitor,PodMonitor,Probe,Prometheus,PrometheusRule,Alertmanager,APIService,Ingress --strict --force-color --ignored-filename-patterns .yml -d apps/
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go get -u github.com/instrumenta/kubeval
      - run: kubeval --skip-kinds Plan,SealedSecret,Application,CustomResourceDefinition,ClusterIssuer,AppProject,ServiceMonitor,PodMonitor,PrometheusRule,Ingress --strict --force-color -d base/
