---
name: kubelint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go get -u go get golang.stackrox.io/kube-linter/cmd/kube-linter
      - run: kube-linter lint apps/
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - run: go get -u go get golang.stackrox.io/kube-linter/cmd/kube-linter
      - run: kube-linter lint base/
