apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: general-rules
  namespace: monitoring
spec:
  groups:
  - name: general.rules
    rules:
    - alert: Watchdog
      annotations:
        summary: "Alerting pipeline test alert"
        description: |
          This is an alert meant to ensure that the entire alerting pipeline is functional.
          This alert is always firing, therefore it should always be firing in Alertmanager
          and always fire against a receiver. There are integrations with various notification
          mechanisms that send a notification when this alert is not firing. For example the
          "DeadMansSnitch" integration in PagerDuty.
      expr: vector(1)
      labels:
        severity: none
    - alert: TargetsDown
      annotations:
        summary: "Prometheus targets went down"
        description: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are down.'
      expr: 100 * (count(up{job!="windows"} == 0) BY (job, namespace, service) / count(up{job!="windows"}) BY (job, namespace, service)) > 10
      for: 10m
      labels:
        severity: warning
    - alert: JobNotCompleted
      expr: |
        ((time() - (job_success_timestamp_seconds > 0)) > job_max_age_seconds)
        or
        (time() - jon_start_timestamp_seconds > job_max_age_seconds and job_success_timestamp_seconds == 0)
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Cron job did not complete"
        description: "Cron job {{ $labels.job }} has not started/completed in {{ $value | humanizeDuration }}"
        runbook_url: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/JobCompletion.md"
  - name: custom node alert rules
    rules:
    - alert: PackagesAvailable
      expr: |
        sum by (node) (yum_upgrades_pending) > 10
        or
        sum by (node) (apt_upgrades_pending) > 10
      for: 48h
      labels:
        severity: info
      annotations:
        summary: "Packages are available for upgrade"
        description: "{{ $value }} packages are available for upgrade. Maybe it is time to upgrade?"
        runbook_url: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/PackagesAvailable.md"
    - alert: RebootRequired
      expr: "node_reboot_required > 0"
      for: 4h
      labels:
        severity: info
      annotations:
        summary: "Reboot is required to finish package upgrade"
        description: "Instance '{{ $labels.instance }}' was upgraded and now requires a reboot."
        runbook_url: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/RebootRequired.md"

