apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: gitops-rules
  namespace: monitoring
spec:
  groups:
    - name: gitops alert rules # Remove all after lancre infra upgrade
      rules:
      - alert: FailedDeploy
        expr: '(increase(deployment_total{status="error"}[20m]) > 0) AND on (instance) (deployment_total{status="success"} == 0)'
        for: '30m'
        labels:
          severity: warning
        annotations:
          description: "Deployment reconcilitaion failed on {{ $labels.instance }} "
          summary: "Deployment failed"
      - alert: DeploymentHalted
        expr: 'sum(increase(deployment_total[30m])) by (instance) < 1'
        for: 1h
        labels:
          severity: warning
        annotations:
          description: "Deployment reconcilitaion is stopped on {{ $labels.instance }} "
          summary: "Deployment halted"
