apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: thaum-rules
  namespace: monitoring
spec:
  groups:
    - name: alert rules specific to thaum.xyz
      rules:
      - alert: BackupNotCreated  # TODO: Remove alert after upgrading infra in lancre
        expr: 'increase(backup_executions_total[48h]) < 1'
        for: 12h
        labels:
          severity: warning
        annotations:
          message: "Backuping up {{ $labels.data }} on {{ $labels.instance }} didn't complete"
      - alert: FederatedPrometheusDown
        expr: 'up{job="lancre"} == 0'
        for: 20m
        labels:
          severity: warning
        annotations:
          message: "Remote Prometheus server {{ $labels.instance }} has been down for more than 10 minutes."
          runbook: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/FederatedPrometheusDown.md"
