apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: thaum-rules
  namespace: monitoring
spec:
  groups:
    - name: alert rules specific to thaum.xyz
      rules:
      - alert: BackupNotCreated  # TODO: Remove alert after upgrading infra in lancre
        expr: 'increase(backup_executions_total[48h]) < 1'
        for: 12h
        labels:
          severity: warning
        annotations:
          message: "Backuping up {{ $labels.data }} on {{ $labels.instance }} didn't complete"
      - alert: FederatedPrometheusDown
        expr: 'up{job="lancre"} == 0'
        for: 20m
        labels:
          severity: warning
        annotations:
          message: "Remote Prometheus server {{ $labels.instance }} has been down for more than 10 minutes."
          runbook: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/FederatedPrometheusDown.md"
      - alert: FilesystemReadOnly
        expr: |
          node_filesystem_readonly{fstype=~"(vfat|ext4|xfs)"} != 0
        labels:
          severity: critical
        annotations:
          message: "Filesystem went read-only possibly due to device error."
          runbook: "Check SD card for FS corruption. Possibly reflash OS to new card."
      - alert: TouchscreenNotAvailable
        expr: |
          devices_input_touchscreen_up == 0
        for: 20m
        labels:
          severity: warning
        annotations:
          message: "Touchscreen not available"
          runbook: "Powercycle device {{ $labels.instance }}"
      - alert: TouchscreenNotAvailable
        expr: |
          devices_input_touchscreen_up == 0
        for: 1h
        labels:
          severity: critical
        annotations:
          message: "Touchscreen not available and automatic remediation failed to restore it"
          runbook: "Powercycle device {{ $labels.instance }}"
