apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: thaum-rules
  namespace: monitoring
spec:
  groups:
  - name: alert rules specific to thaum.xyz
    rules:
    - alert: FederatedPrometheusDown
      expr: 'up{job="lancre"} == 0'
      for: 20m
      labels:
        severity: warning
      annotations:
        summary: "Federated prometheus is down"
        description: "Remote Prometheus server {{ $labels.instance }} has been down for more than 10 minutes."
        runbook_url: "https://github.com/thaum-xyz/ankhmorpork/blob/master/docs/runbooks/FederatedPrometheusDown.md"
    - alert: FilesystemReadOnly
      expr: |
        node_filesystem_readonly{fstype=~"(vfat|ext4|xfs)"} != 0
      labels:
        severity: critical
      annotations:
        summary: "Filesystem went read-only possibly due to device error."
        description: "Filesystem went read-only on {{ $labels.instance }}. Check FS for possible corruption."
    - alert: TouchscreenNotAvailable
      expr: |
        devices_input_touchscreen_up == 0 or absent(devices_input_touchscreen_up)
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Touchscreen not available"
        description: "Powercycle device {{ $labels.instance }} to bring touchscreen up"
    - alert: TouchscreenNotAvailable
      expr: |
        devices_input_touchscreen_up == 0 or absent(devices_input_touchscreen_up)
      for: 1h
      labels:
        severity: critical
      annotations:
        summary: "Touchscreen not available and automatic remediation failed to restore it"
        description: "Powercycle device {{ $labels.instance }}"
    - alert: TemperaturesNotAvailable
      expr: |
        absent(evok_temperature_celsius)
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "Cannot obtain temperature data"
        description: "Temperature data is gone. Immediatelly switch off all relays and check OW bus."
