---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: radarr
  namespace: multimedia
  labels:
    app.kubernetes.io/name: radarr
spec:
  podMetricsEndpoints:
  - port: metrics
    interval: 3m
    scrapeTimeout: 90s
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
