---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updater
  namespace: dns
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: curlimages/curl:7.70.0
            command:
            - /bin/sh
            - -c
            - "curl --user $USER:$PASS \"https://www.ovh.com/nic/update?system=dyndns&hostname=$DOMAIN&myip=$(curl https://ipecho.net/plain 2>/dev/null)\" 2>/dev/null"
            env:
            - name: DOMAIN
              value: "ankhmorpork.thaum.xyz"
            - name: USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: credentials
            - name: PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: credentials
          restartPolicy: OnFailure
